import { FormContainer } from "@/components/common/form/FormContainer";
import { FormInput } from "@/components/common/form/FormInput";
import SubmitButtons from "@/components/common/form/SubmitButtons";
import RootLayout from "@/layout";
import { createProfileAction } from "@/utils/actions";
import Head from "next/head";

function createProfilePage() {
    return (
        <>
            <Head>
                <title>Arbnb - Profile Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-3xl font-bold underline">
                <RootLayout>
                    <section>
                        <h1 className='text-2xl font-semibold mb-8 capitalize'>new user</h1>
                        <div className='border p-8 rounded-md max-w-lg'>
                            <FormContainer action={createProfileAction}>
                                <div className='grid gap-4 mt-4 '>
                                    <FormInput type='text' name='firstName' label='First Name' isRequired={true} />
                                    <FormInput type='text' name='lastName' label='Last Name' isRequired={true} />
                                    <FormInput type='text' name='username' label='Username' isRequired={true} />
                                    <SubmitButtons text='Create Profile' className='mt-8' />
                                </div>
                            </FormContainer>
                        </div>
                    </section>
                </RootLayout>
            </div>
        </>
    );
}

export default createProfilePage;