import RootLayout from "@/layout";
import Head from "next/head";

function ProfilePage() {
  return (
    <>
      <Head>
        <title>Arbnb - Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <RootLayout>
          Profile Page - 22
        </RootLayout>
      </div>
    </>
  );
}
export default ProfilePage;
