import Head from "next/head";
import type { Metadata } from "next";
import RootLayout from "@/layout";

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Feel at home, away from home.",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Arbnb - Feel at home, away from home.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl font-bold underline">
        <RootLayout>
         <div>home page</div>
        </RootLayout>
      </div>
    </>
  );
}
